twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals:
        message_limit: 3

when@test:
    twig:
        strict_variables: true
